package com.vaadin.book.examples.editor;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;

public class MyComponent extends CustomComponent {
    private static final long serialVersionUID = 4022868770736162630L;
    
    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private ComboBox comboBox_1;
    @AutoGenerated
    private CheckBox checkBox_1;
    @AutoGenerated
    private Button button_1;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public MyComponent() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }
    
    public CheckBox getCheckBox_1() {
        return checkBox_1;
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // button_1
        button_1 = new Button();
        button_1.setCaption("Button");
        button_1.setImmediate(true);
        button_1.setWidth("-1px");
        button_1.setHeight("-1px");
        mainLayout.addComponent(button_1, "bottom:212.0px;left:214.0px;");
        
        // checkBox_1
        checkBox_1 = new CheckBox();
        checkBox_1.setCaption("CheckBox");
        checkBox_1.setImmediate(false);
        checkBox_1.setWidth("-1px");
        checkBox_1.setHeight("-1px");
        mainLayout.addComponent(checkBox_1, "top:240.0px;left:60.0px;");
        
        // comboBox_1
        comboBox_1 = new ComboBox();
        comboBox_1.setImmediate(false);
        comboBox_1.setWidth("-1px");
        comboBox_1.setHeight("-1px");
        mainLayout.addComponent(comboBox_1, "top:200.0px;left:400.0px;");
        
        return mainLayout;
    }
}

